name: Secvisogram CI

on:
  pull_request:
  push:
    branches: [main, main-fork]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
      - run: npm ci
      - run: cd app && npx eslint --max-warnings 0
      - run: npm run-script build
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.1-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run-script test
